import { SingUpUserCase } from "../Application/UseCase/SingUpUserCase";
import { GetByUserCase } from "../Application/UseCase/GetByUserCase";
import { UpdateUserUseCase } from "../Application/UseCase/UpdateUserCase";
import { DeleteUserCase } from "../Application/UseCase/DeleteUserCase";
import { ListUsersCase } from "../Application/UseCase/ListUsersCase";
import { SingInUserController } from "./Controllers/SingInUserController";
import { SingUpUserController } from "./Controllers/SingUpUserController";
import { SingOutUserController } from "./Controllers/SingOutUserController";
import { DeleteUserController } from "./Controllers/DeleteUserController";
import GetByEmailController from "./Controllers/GetByEmailController";
import GetByUuidController from "./Controllers/GetByUuidController";
import { UpdateUserController } from "./Controllers/UpdateUserController";
import { ListUsersController } from "./Controllers/ListUsersController";
import { ActivateUserCase } from "../Application/UseCase/ActivateUserCase";
import { ActivateUserController } from "./Controllers/ActivateUserController";
import { MysqlUserRepository } from "../Infraestructure/Repositories/MysqlUserRepository";
import { MongoDBUserRepository } from "../Infraestructure/Repositories/MongoUserRepository";
import { SqliteUserRepository } from "./Repositories/SqliteUserRepository";
import { NodemailerEmailService } from "./Services/NodemailerEmailService";
import { ByEncryptServices } from "./Services/ByEncryptServices";
import { SingInUserCase } from "../Application/UseCase/SingInUserCase";
import { SingOutUserCase } from "../Application/UseCase/SingOutUserCase";
import { TokenServices } from "./Services/TokenServices";
import { DeleteHotelValorationCase } from "../Application/UseCase/DeleteHotelValorationCase";
import { MongoHotelValorationsRepository } from "./Repositories/MongoHotelValorationsRepository";
import { GetHotelValorationsByHotelCase } from "../Application/UseCase/GetHotelValorationsByHotelCase";
import { GetHotelValorationsByUserCase } from "../Application/UseCase/GetHotelValorationsByUserCase";
import { SaveHotelValorationsCase } from "../Application/UseCase/SaveHotelValorationsCase";
import { UpdateHotelValorationsCase } from "../Application/UseCase/UpdateHotelValorationCase";
import { DeleteHotelValorationController } from "./Controllers/DeleteHotelValorationController";
import { GetHotelValorationsByHotelController } from "./Controllers/GetHotelValorationsByHotelController";
import { SaveHotelValorationsController } from "./Controllers/SaveHotelValorationsController";
import { UpdateHotelValorationController } from "./Controllers/UpdateHotelValorationController";

export const databaseRepository = new MongoDBUserRepository();
export const databaseRepositoryHotel= new MongoHotelValorationsRepository();

export const encriptServices = new ByEncryptServices();
export const nodemailerEmailService = new NodemailerEmailService();
export const tokenServices = new TokenServices();

export const singUpUserCase = new SingUpUserCase(databaseRepository);
export const getUserUseCase = new GetByUserCase(databaseRepository);
export const updateUserUseCase = new UpdateUserUseCase(databaseRepository);
export const deleteUserUseCase = new DeleteUserCase(databaseRepository);
export const listUsersCase = new ListUsersCase(databaseRepository);
export const activateUserCase = new ActivateUserCase(databaseRepository);
export const singInUserCase = new SingInUserCase(databaseRepository);
export const singOutUserCase = new SingOutUserCase(databaseRepository);
export const deleteHotelValorationCase = new DeleteHotelValorationCase(databaseRepositoryHotel);
export const getHotelValorationsByHotelCase = new GetHotelValorationsByHotelCase(databaseRepositoryHotel);
export const getHotelValorationsByUserCase = new GetHotelValorationsByUserCase(databaseRepositoryHotel);
export const saveHotelValorationsCase = new SaveHotelValorationsCase(databaseRepositoryHotel);
export const updateHotelValorationCase = new UpdateHotelValorationsCase(databaseRepositoryHotel);

export const singInUserController = new SingInUserController(singInUserCase, encriptServices, tokenServices);
export const singUpUserController = new SingUpUserController(singUpUserCase,nodemailerEmailService, encriptServices);
export const deleteUserController = new DeleteUserController(deleteUserUseCase);
export const getByUuidController = new GetByUuidController(getUserUseCase);
export const getByEmailController = new GetByEmailController(getUserUseCase);
export const updateUserController = new UpdateUserController(updateUserUseCase, encriptServices);
export const listUsersController = new ListUsersController(listUsersCase);
export const activateUserController = new ActivateUserController(activateUserCase);
export const singOutUserController = new SingOutUserController(singOutUserCase);
export const deleteHotelValorationController = new DeleteHotelValorationController(deleteHotelValorationCase);
export const getHotelValorationsByHotelController = new GetHotelValorationsByHotelController(getHotelValorationsByHotelCase);
export const getHotelValorationsByUserController = new GetHotelValorationsByHotelController(getHotelValorationsByUserCase);
export const saveHotelValorationsController = new SaveHotelValorationsController(saveHotelValorationsCase);
export const updateHotelValorationController = new UpdateHotelValorationController(updateHotelValorationCase);
