version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb_hex
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    networks:
      - api_hex

volumes:
  data: {}

networks:
  api_hex:
    name: api_hex
