import { MongoHotelRepository } from "./Repositories/MongoHotelRepository";
import  MongoServiceRepository  from "./Repositories/MongoServiceRepository";
import { AddImageHotelCase } from "../Application/UseCase/AddImageHotelCase"; // Import the AddImageHotelCase class
import { GetByNameHotelCase } from "../Application/UseCase/GetByNameHotelCase";
import { UpdateHotelCase } from "../Application/UseCase/UpdateHotelCase";
import { DeleteHotelCase } from "../Application/UseCase/DeleteHotelCase";
import { DeleteServiceCase } from "../Application/UseCase/DeleteServiceCase";
import { CreateHotelCase } from "../Application/UseCase/CreateHotelCase";
import { CreateServiceCase } from "../Application/UseCase/CreateServiceCase";
import { DeleteHotelImagesCase } from "../Application/UseCase/DeleteHotelImagesCase";
import { DeleteHotelRoomCase } from "../Application/UseCase/DeleteHotelRoomCase";
import { GetByUuidHotelCase } from "../Application/UseCase/GetByUuidHotelCase";
import { GetByUuidServiceCase } from "../Application/UseCase/GetByUuidServiceCase";
import { ListHotelCase } from "../Application/UseCase/ListHotelCase";
import { ListHotelImagesCase } from "../Application/UseCase/ListHotelImagesCase";
import { ListHotelRoomCase } from "../Application/UseCase/ListHotelRoomCase";
import { RegisterHotelRoomCase } from "../Application/UseCase/RegisterHotelRoomCase";
import { ListServiceCase } from "../Application/UseCase/ListServiceCase";
import { CreateHotelController } from "./Controllers/CreateHotelController";
import { CreateServiceController } from "./Controllers/CreateServiceController";
import { DeleteHotelController } from "./Controllers/DeleteHotelController";
import { DeleteHotelImagesController } from "./Controllers/DeleteHotelImagesController";
import { DeleteHotelRoomController } from "./Controllers/DeleteHotelRoomController";
import { DeleteServiceController } from "./Controllers/DeleteServiceController";
import GetByUuidHotelController from "./Controllers/GetByUuidHotelController";
import GetByNameHotelController from "./Controllers/GetByNameHotelController";
import GetByUuidServiceController from "./Controllers/GetByUuidServiceController";
import ListHotelController from "./Controllers/ListHotelController";
import ListHotelImagesController from "./Controllers/ListHotelImagesController";
import ListServiceController from "./Controllers/ListServiceController";
import ListHotelRoomController from "./Controllers/ListHotelImagesController";
import ListHotelRoomsController from "./Controllers/ListHotelRoomsController";
import { RegisterHotelRoomController } from "./Controllers/RegisterHotelRoomController";
import { UpdateHotelController } from "./Controllers/UpdateHotelController";
import { UpdateServiceController } from "./Controllers/UpdateServiceController";
import { UpdateServiceCase } from "../Application/UseCase/UpdateServiceCase";

export const databaseHotelRepository = new MongoHotelRepository();
export const databaseServicesRepository = new MongoServiceRepository();

export const addImageHotelCase = new AddImageHotelCase(databaseHotelRepository);
export const createHotelCase = new CreateHotelCase(databaseHotelRepository);
export const deleteHotelCase = new DeleteHotelCase(databaseHotelRepository);
export const deleteHotelImagesCase = new DeleteHotelImagesCase(databaseHotelRepository);
export const deleteHotelRoomCase = new DeleteHotelRoomCase(databaseHotelRepository);
export const getByNameHotelCase = new GetByNameHotelCase(databaseHotelRepository);
export const getByUuidHotelCase = new GetByUuidHotelCase(databaseHotelRepository);
export const listHotelCase = new ListHotelCase(databaseHotelRepository);
export const listHotelImagesCase = new ListHotelImagesCase(databaseHotelRepository);
export const listHotelRoomCase = new ListHotelRoomCase(databaseHotelRepository);
export const registerHotelRoomCase = new RegisterHotelRoomCase(databaseHotelRepository);
export const updateHotelCase = new UpdateHotelCase(databaseHotelRepository);

export const createServiceCase = new CreateServiceCase(databaseServicesRepository);
export const deleteServiceCase = new DeleteServiceCase(databaseServicesRepository);
export const getByUuidServiceCase = new GetByUuidServiceCase(databaseServicesRepository);
export const listServicesCase = new ListServiceCase(databaseServicesRepository);
export const updateServiceCase = new UpdateServiceCase(databaseServicesRepository);

export const createHotelController = new CreateHotelController(createHotelCase);
export const deleteHotelController = new DeleteHotelController(deleteHotelCase);
export const deleteHotelImagesController = new DeleteHotelImagesController(deleteHotelImagesCase);
export const deleteHotelRoomController = new DeleteHotelRoomController(deleteHotelRoomCase);
export const getByUuidHotelController = new GetByUuidHotelController(getByUuidHotelCase);
export const getByNameHotelController = new GetByNameHotelController(getByNameHotelCase);
export const listHotelController = new ListHotelController(listHotelCase);
export const listHotelImagesController = new ListHotelImagesController(listHotelImagesCase);
export const listHotelRoomController = new ListHotelRoomsController(listHotelRoomCase);
export const registerHotelRoomController = new RegisterHotelRoomController(registerHotelRoomCase);
export const updateHotelController = new UpdateHotelController(updateHotelCase);

export const createServiceController = new CreateServiceController(createServiceCase);
export const deleteServiceController = new DeleteServiceController(deleteServiceCase);
export const getByUuidServiceController = new GetByUuidServiceController(getByUuidServiceCase);
export const listServiceController = new ListServiceController(listServicesCase);
export const updateServiceController = new UpdateServiceController(updateServiceCase);